name: Automated Tests

on: pull_request
jobs:
  jest: Jest Ubuntu
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - uses: actions/node@v4
      with:
        node-version: "lts/hydrogen"

    - run: npm ci

    - run: npm test
